example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path
from katalog.views import show_catalog

app_name = 'katalog'

urlpatterns = [
    path('', show_catalog, name='katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_watchlist_html, show_watchlist_xml, show_watchlist_json, wathclist_links

app_name = 'mywatchlist'

urlpatterns = [
    path('', wathclist_links, name='watchlist'),
    path('html/', show_watchlist_html, name='watchlist_html'),
    path('xml/', show_watchlist_xml, name='watchlist_xml'),
    path('json/', show_watchlist_json, name='watchlist_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import *

app_name = 'todolist'

urlpatterns = [
    path('', todolist, name='todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create_task/', create_task, name='create_task'),
    path('change/<int:id>', change_status, name='change_status'),
    path('delete/<int:id>', delete, name='delete'),
    path('json/', todolist_json, name='todolist_json'),
    path('add/', add_task, name='add_task')
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class MyWatchList(models.Model):
    watched = models.BooleanField()
    title = models.CharField(max_length=255)
    rating = models.IntegerField()
    release_date = models.DateField()
    review = models.CharField(max_length=255)

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms

class TaskForm(forms.Form):
    title = forms.CharField(label="Judul", max_length=100, widget=forms.TextInput(attrs={"id":"input-title"}))
    description = forms.CharField(label="Deskripsi", max_length=250, widget=forms.TextInput(attrs={"id":"input-desc"}))

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

def show_catalog(req):
    catalog_data = CatalogItem.objects.all()    
    context = {
        "nama": "Bonaventura Galang Kristabel Angipanglipur Hatmasasmita",
        "npm": "2106630025",
        "catalog_data": catalog_data
    }
    return render(req, "katalog/index.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def show_watchlist_html(req):
    watchlist = MyWatchList.objects.all()

    films_watched = 0
    films_not_watched = 0
    for film in watchlist:
        if film.watched:
            films_watched += 1
        else:
            films_not_watched += 1

    context = {
        "nama": "Bonaventura Galang Kristabel Angipanglipur Hatmasasmita",
        "npm": "2106630025",
        "watchlist": watchlist,
        "films_watched": films_watched,
        "films_not_watched": films_not_watched
    }
    return render(req, "watchlist.html", context)

def show_watchlist_xml(req):
    watchlist = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", watchlist), content_type="application/xml")

def show_watchlist_json(req):
    watchlist = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", watchlist), content_type="application/json")

def wathclist_links(req):
    context = {
        "nama": "Bonaventura Galang Kristabel Angipanglipur Hatmasasmita",
        "npm": "2106630025",
    }
    return render(req, "watchlist_links.html", context)

todolist/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.core import serializers
from django.http import JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from todolist.models import Task
from todolist.forms import TaskForm
import datetime

# Create your views here.
@login_required(login_url='/todolist/login/')
def todolist(req):
    list_task = Task.objects.filter(user=req.user)
    context = {
        'list_task': list_task,
        'username': req.user.username,
        "form": TaskForm()
    }
    return render(req, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def todolist_json(req):
    list_task = Task.objects.filter(user=req.user)
    return HttpResponse(serializers.serialize("json", list_task), content_type="application/json")

@login_required(login_url='/todolist/login/')
def create_task(req):
    if req.method == "POST":
        form = TaskForm(req.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            Task.objects.create(title=title, description=description, date=datetime.date.today(), user=req.user)
            return redirect('todolist:todolist')
    else:
        form = TaskForm()

    return render(req, "add_task.html", context={"form": form, "username": req.user.username})

@login_required(login_url='/todolist/login/')
def add_task(req):
    if req.method == "POST":
        form = TaskForm(req.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            task = Task.objects.create(title=title, description=description, date=datetime.date.today(), user=req.user)
            data = {
                "pk": task.pk,
                "title": task.title,
                "description": task.title,
                "is_finished": task.is_finished,
                "date": task.date
            }
            return JsonResponse(data)
    
    return HttpResponseBadRequest()

@login_required(login_url='/todolist/login/')
def change_status(req, id):
    task = Task.objects.get(id=id)
    task.is_finished = not(task.is_finished)
    task.save()
    return redirect('todolist:todolist')

@login_required(login_url='/todolist/login/')
@csrf_exempt
def delete(req, id):
    Task.objects.get(id=id).delete()
    return HttpResponse()

def register(req):
    form = UserCreationForm()

    if req.method == "POST":
        form = UserCreationForm(req.POST)
        if form.is_valid():
            form.save()
            messages.success(req, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(req, 'register.html', context)

def login_user(req):
    if req.method == 'POST':
        username = req.POST.get('username')
        password = req.POST.get('password')
        user = authenticate(req, username=username, password=password)
        if user is not None:
            login(req, user)
            response = HttpResponseRedirect(reverse("todolist:todolist")) # membuat response
            return response
        else:
            messages.info(req, 'Username atau Password salah!')
    context = {}
    return render(req, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/index.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>Fill me!</p>

  <h5>Student ID: </h5>
  <p>Fill me!</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
  </table>

 {% endblock content %}

katalog/templates/katalog/index.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for katalog in catalog_data %}
        <tr>
            <td>{{katalog.item_name}}</td>
            <td>{{katalog.item_price}}</td>
            <td>{{katalog.item_stock}}</td>
            <td>{{katalog.rating}}</td>
            <td>{{katalog.description}}</td>
            <td>{{katalog.item_url}}</td>
        </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/watchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Assignment 3 PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table>
    <tr>
      <th>Title</th>
      <th>Release Date</th>
      <th>Rating</th>
      <th>Review</th>
      <th>Watched</th>
    </tr>

    {% for film in watchlist %}
        <tr>
            <td>{{film.title}}</td>
            <td>{{film.release_date}}</td>
            <td>{{film.rating}}</td>
            <td>{{film.review}}</td>
            <td>{{film.watched}}</td>
        </tr>
    {% endfor %}
  </table>

  {% if films_watched >= films_not_watched %}
    <p>Selamat, kamu sudah banyak menonton!</p>
  {% else %}
    <p>Wah, kamu masih sedikit menonton!</p>
  {% endif %}

 {% endblock content %}

mywatchlist/templates/watchlist_links.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Assignment 3 PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <h3>Links</h3>
  <a href="/mywatchlist/html">HTML</a>
  <a href="/mywatchlist/xml">XML</a>
  <a href="/mywatchlist/json">JSON</a>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="{% static "css/output.css" %}" rel="stylesheet">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/add_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Buat Task</title>
{% endblock meta %}

{% load filters %}

{% block content %}  

<div class="bg-gainsboro h-screen overflow-hidden">
  {% include 'navbar.html' %}
  <div class="flex flex-col justify-center h-full">
    <div class="flex justify-center">
      <div class = "flex flex-col bg-robin-egg-blue rounded-lg p-8 gap-4 drop-shadow-2xl">
              
          <h1 class="text-xl font-semibold">Buat Task</h1>

          <div class="border-b-2 border-corn my-2"></div>
      
              <form method="POST" >
                  {% csrf_token %}
                  <div class="flex flex-col gap-4">
                    <div class="flex gap-4">
                      <div class="flex flex-col justify-around gap-2">
                        <p>Title:</p>
                        <p>Description:</p>
                      </div>
                      <div class="flex flex-col justify-around gap-2">
                        {{ form.title|addclass:"rounded p-1"}}
                        {{ form.description|addclass:"rounded p-1"}}
                      </div>
                    </div>
                    <div class="bg-gainsboro rounded mx-20 border-2 border-quick-silver active:bg-quick-silver active:shadow-lg active:border-black">
                      <input class="p-1 w-full h-full" name="submit" value="Buat Task" type="submit" />
                    </div>
                    {{ form.title.errors }}
                    {{ form.description.errors }}
                  </div>
              </form>
      
          {% if messages %}  
              <ul>   
                  {% for message in messages %}  
                      <li>{{ message }}</li>  
                      {% endfor %}  
              </ul>   
          {% endif %}
      </div>  
    </div>
  </div>
</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class="flex flex-col h-screen justify-center bg-ivory">
  <div class="flex justify-center">
    <div class="login flex flex-col bg-robin-egg-blue rounded-lg p-8 gap-4 drop-shadow-2xl">
    
        <h1 class="text-xl font-semibold">Login</h1>
        <div class="border border-corn mb-2"></div>
    
        <form method="POST" action="">
            {% csrf_token %}
            <div class="flex flex-col gap-2">
              <div class="flex gap-4">
                <div class="flex flex-col justify-around gap-2">
                  <p>Username:</p>
                  <p>Password:</p>
                </div>
                <div class="flex flex-col justify-around gap-2">
                  <input type="text" name="username" placeholder="Username" class="form-control rounded p-1"></td>
                  <input type="password" name="password" placeholder="Password" class="form-control rounded p-1">
                </div>
              </div>
              <input class="btn login_btn bg-gainsboro rounded p-1 mx-20 border-2 border-quick-silver active:bg-quick-silver active:shadow-lg active:border-black" type="submit" value="Login">
            </div>
        </form>
    
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
        
        <p class="text-xs">Belum mempunyai akun? <span><a href="{% url 'todolist:register' %}" class="underline text-corn">Buat Akun</a><span></p>
    
    </div>
  </div>
</div>

{% endblock content %}

todolist/templates/navbar.html
<div class="fixed top-0 w-screen bg-robin-egg-blue rounded shadow-lg">
  <div class="flex py-4 px-8 gap-8 justify-between">
    <div class="flex flex-col md:flex-row gap-4">
      <div class="flex flex-col justify-center">
        <p class="text-3xl font-bold text-corn">Todolist</p>
      </div>
      <div class="flex gap-4">
        <div class="flex flex-col justify-center">
          <a class="text-lg text-ivory" href="{% url 'todolist:todolist' %}">Home</a>
        </div>
        <div class="flex flex-col justify-center">
          {% comment %} <a class="text-lg text-ivory" href="{% url 'todolist:create_task' %}">Buat Task</a> {% endcomment %}
          <button class="text-lg text-ivory" id="open-modal">Buat Task</button>
        </div>
      </div>
    </div>
    <div class="flex">
      <div class="flex gap-4">
        <div class="hidden md:flex flex-col justify-center">
          <p class="text-lg font-semibold text-ivory">Hello, {{ username }}!</p>
        </div>
        <div class="flex flex-col justify-center">
          <div class="rounded bg-ivory py-1">
            <a class="text-lg font-semibold text-orange-red w-full px-2" href="{% url 'todolist:logout' %}">Logout</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% load filters %}

{% block content %}  

<div class="flex flex-col h-screen justify-center bg-ivory">
  <div class="flex justify-center">
    <div class = "login flex flex-col bg-robin-egg-blue rounded-lg p-8 gap-4 drop-shadow-2xl">
        
        <h1 class="text-xl font-semibold">Register</h1>
        <div class="border border-corn mb-2"></div>
    
            <form method="POST" >
                {% csrf_token %}
                <div class="flex flex-col gap-2">
                  <div class="flex gap-4">
                    <div class="flex flex-col justify-around gap-2">
                      <p>Username:</p>
                      <p>Password:</p>
                      <p>Confirm Password:</p>
                    </div>
                    <div class="flex flex-col justify-around gap-2">
                      {{ form.username|addclass:"rounded p-1"}}
                      {{ form.password1|addclass:"rounded p-1"}}
                      {{ form.password2|addclass:"rounded p-1"}}
                    </div>
                  </div>
                  <td><input type="submit" name="submit" value="Daftar" class="bg-gainsboro rounded p-1 mx-20 border-2 border-quick-silver active:bg-quick-silver active:shadow-lg active:border-black"/></td>  
                  {{ form.username.errors }}
                  {{ form.password1.errors }}
                  {{ form.password2.errors }}
                </div>
            </form>
    
        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>   
        {% endif %}
        <p class="text-xs">Sudah mempunyai akun? <span><a href="{% url 'todolist:login' %}" class="underline text-corn">Login</a><span></p>
    </div>  
  </div>
</div>

{% endblock content %}

todolist/templates/task_card.html
<div class="bg-ivory rounded-lg p-4 shadow-md hover:shadow-xl hover:shadow-gray-400" id="task-{{ id }}">
  <div class="flex flex-col">
    <div class="flex justify-between gap-8">
      <div class="flex flex-col justify-center">
        <p class="text-lg font-semibold">{{ task.title }}</p>
      </div>
      <div class="flex flex-col justify-center">
        <p class="text-xs font-semibold">{{ task.date }}</p>
      </div>
    </div>
    
    <div class="border-b-2 border-robin-egg-blue my-2"></div>

    <div class="flex flex-col gap-2">  
      {% if task.is_finished %}
        <p class="text-sm font-bold text-green-apple">Finished</p>
      {% else %}
        <p class="text-sm font-bold text-orange-red">Not Finished</p>
      {% endif %}
  
      <p>{{ task.description }}</p>
  
      <div class="flex justify-between gap-4">
        <div class="flex flex-col justify-center rounded bg-orange-red">
          <a class="text-ivory w-full h-full px-2 py-1" href="{% url 'todolist:delete' task.id %}">Delete</a>
        </div>
        <div class="flex flex-col justify-center rounded bg-robin-egg-blue">
          <a class="text-ivory w-full h-full px-2 py-1" href="{% url 'todolist:change_status' task.id %}">Change Status</a>
        </div>
      </div>
    </div>
  </div>
</div>

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  const makeCard = (task) => `
  <div class="bg-ivory rounded-lg p-4 shadow-md hover:shadow-xl hover:shadow-gray-400" id="task-${task.pk}">
    <div class="flex flex-col">
      <div class="flex justify-between gap-8">
        <div class="flex flex-col justify-center">
          <p class="text-lg font-semibold">${task.title}</p>
        </div>
        <div class="flex flex-col justify-center">
          <p class="text-xs font-semibold">${task.date}</p>
        </div>
      </div>
      
      <div class="border-b-2 border-robin-egg-blue my-2"></div>
  
      <div class="flex flex-col gap-2">
        ${task.is_finished ? 
          `<p class="text-sm font-bold text-green-apple">Finished</p>` : 
          `<p class="text-sm font-bold text-orange-red">Not Finished</p>`}
        <p>${task.description}</p>
    
        <div class="flex justify-between gap-4">
          <div class="flex flex-col justify-center rounded bg-orange-red">
            <button class="text-ivory w-full h-full px-2 py-1" onClick="deleteTask(${task.pk})"'>Delete</button>
          </div>
          <div class="flex flex-col justify-center rounded bg-robin-egg-blue">
            <a class="text-ivory w-full h-full px-2 py-1" href='/todolist/change/${task.pk}'>Change Status</a>
          </div>
        </div>
      </div>
    </div>
  </div>`

  const showTask = () => {
    $.get("/todolist/json/", (data) => {
      for(var i = 0; i < data.length; i++){
        var task = {
          pk : data[i].pk,
          ...data[i].fields
        };
        $("#task-cards").append(makeCard(task));
      }
    }
  )};
  
  const openModal = () => {
    $("#modal").removeClass("hidden");
  }
  
  const closeModal = () => {
    $("#modal").addClass("hidden");
  }
  
  const postTask = (task) => {
    $.post("/todolist/add/", {
      ...task,
      csrfmiddlewaretoken: "{{ csrf_token }}"
    },
    (data, status) => {
      console.log(data);
      $("#task-cards").append(makeCard(data));
      closeModal();
    });
  }

  const deleteTask = (pk) => {
    $.ajax({
      type: "DELETE",
      url: `/todolist/delete/${pk}`,
      success: (data) => {
        $(`#task-${pk}`).remove();
      }
    });
  }

  $(document).ready(() => {
    showTask();

    $("#open-modal").click(() => {
      openModal();
    });

    $("#close-modal").click(() => {
      closeModal();
    });

    $("#submit-task").click(() => {
      const task = {
        title: $("#input-title").val(),
        description: $("#input-desc").val()
      }
      postTask(task);
      return false;
    });
  });
</script>
{% endblock meta %}

{% load filters %}

{% block content %}
<div class="bg-gainsboro h-screen overflow-auto">
  {% include 'navbar.html' %}

  <div class="flex flex-col p-8 pt-28">
    <div class="flex flex-wrap justify-center gap-8" id="task-cards">
    </div>
  </div>

</div>

<div id="modal" class="hidden absolute top-0 h-screen w-screen flex flex-col justify-center bg-[#1E313BAC]">
  <div class="flex justify-center">
    <div class = "flex flex-col bg-robin-egg-blue rounded-lg p-8 gap-4 drop-shadow-2xl">
      
      <div class="flex justify-between">
        <h1 class="text-xl font-semibold">Buat Task</h1>
        <div>
          <button id="close-modal" class="rounded">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>        
          </button>
        </div>
      </div>
  
      <div class="border-b-2 border-corn my-2"></div>
  
          <form method="" >
              {% csrf_token %}
              <div class="flex flex-col gap-4">
                <div class="flex gap-4">
                  <div class="flex flex-col justify-around gap-2 grow">
                    <p>Title:</p>
                    {{ form.title|addclass:"md:hidden rounded p-1"}}
                    <p>Description:</p>
                    {{ form.description|addclass:"md:hidden rounded p-1"}}
                  </div>
                  <div class="md:flex flex-col justify-around gap-2 hidden">
                    {{ form.title|addclass:"hidden md:flex rounded p-1"}}
                    {{ form.description|addclass:"hidden md:flex rounded p-1"}}
                  </div>
                </div>
                <div class="bg-gainsboro rounded mx-20 border-2 border-quick-silver active:bg-quick-silver active:shadow-lg active:border-black">
                  <button id="submit-task" class="p-1 w-full h-full" name="submit">Buat Task</button>
                </div>
                {{ form.title.errors }}
                {{ form.description.errors }}
              </div>
            </form>
  
      {% if messages %}  
          <ul>   
              {% for message in messages %}  
                  <li>{{ message }}</li>  
                  {% endfor %}  
          </ul>   
      {% endif %}
    </div>
  </div>
</div>

{% endblock content %}